name: ci

on:
  push:
    branches:
      - 'development'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: alanssitis/test:latest
      - 
        name: Print stuff
        run: |
          echo ${{ steps.build-and-push.outputs }}
