name: container-build

on:
  push:
    branches:
      - 'development'

env:
  IMAGE_NAME: docker.io/alanssitis/test

jobs:
  
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout repo
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          image: $${{ env.IMAGE_NAME }}
          tags: docker
      - 
        name: Print stuff
        run: |
          pip install -r requirements.txt
          echo '${{ steps.build-and-push.outputs.metadata }}'
          python3 resolve_gh_action.py 'docker' '${{ env.IMAGE_NAME }}' '${{ steps.build-and-push.outputs.digest }}'

  buildah:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout repo
        uses: actions/checkout@v3
      - 
        name: Build Image
        uses: redhat-actions/buildah-build@v2
        id: build-image
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: buildah
          containerfiles: |
            ./Dockerfile
      -
        name: Push Image
        id: push-image
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: docker.io/alanssitis
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Print stuff
        run: |
          pip install -r requirements.txt
          echo '${{ steps.push-image.outputs.registry-paths }}'
          python3 resolve_gh_action.py 'buildah' '${{ env.IMAGE_NAME }}' '${{ steps.push-image.outputs.digest }}'
